# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/neev',
                'doc_host': 'https://nasheqlbrm.github.io',
                'git_url': 'https://github.com/nasheqlbrm/neev',
                'lib_path': 'neev'},
  'syms': {'neev.core': {'neev.core.foo': ('core.html#foo', 'neev/core.py')}}}
