# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/neev',
                'doc_host': 'https://nasheqlbrm.github.io',
                'git_url': 'https://github.com/nasheqlbrm/neev',
                'lib_path': 'neev'},
  'syms': { 'neev.engine': { 'neev.engine.Value': ('engine.html#value', 'neev/engine.py'),
                             'neev.engine.Value.__add__': ('engine.html#value.__add__', 'neev/engine.py'),
                             'neev.engine.Value.__init__': ('engine.html#value.__init__', 'neev/engine.py'),
                             'neev.engine.Value.__mul__': ('engine.html#value.__mul__', 'neev/engine.py'),
                             'neev.engine.Value.__repr__': ('engine.html#value.__repr__', 'neev/engine.py')},
            'neev.viz': { 'neev.viz.get_dot': ('viz.html#get_dot', 'neev/viz.py'),
                          'neev.viz.trace': ('viz.html#trace', 'neev/viz.py'),
                          'neev.viz.view_dot': ('viz.html#view_dot', 'neev/viz.py')}}}
