# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_engine.ipynb.

# %% auto 0
__all__ = ['Value']

# %% ../nbs/00_engine.ipynb 3
import math
import numpy as np
import matplotlib.pyplot as plt

# %% ../nbs/00_engine.ipynb 18
class Value:
    '''stores a single scalar value and its gradient'''
    def __init__(self, 
                 data,# a scalar value
                 _children=(),# The children of this value
                 _op='',# The operation (+,-,* or tanh) that created this value
                 label=''):
        self.data, self._prev, self._op = data, set(_children), _op
        self.label = label 
        self.grad = 0 # derivative of the Loss with respect to this value
        
    def __add__(self, other):
        out = Value(self.data + other.data, (self,other), '+')
        return out
    
    def __mul__(self, other):
        out = Value(self.data * other.data, (self,other),'*')
        return out
    
    def tanh(self):
        x = self.data
        t = (math.exp(2*x)-1.)/(math.exp(2*x)+1.)
        out = Value(t,(self,),'tanh',)
        return out
    
    def __repr__(self):
        return f'Value(data={self.data})'
