# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_engine.ipynb.

# %% auto 0
__all__ = ['Value']

# %% ../nbs/00_engine.ipynb 2
import math
import numpy as np
import matplotlib.pyplot as plt

# %% ../nbs/00_engine.ipynb 21
class Value:
    '''stores a single scalar value and its gradient'''
    def __init__(self, data):
        self.data = data
        
    def __add__(self, other):
        out = Value(self.data + other.data)
        return out
    
    def __mul__(self, other):
        out = Value(self.data * other.data)
        return out
    
    def __repr__(self):
        return f'Value(data={self.data})'
