# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_viz.ipynb.

# %% auto 0
__all__ = ['trace', 'draw_dot']

# %% ../nbs/01_viz.ipynb 3
from graphviz import Digraph
from .engine import *

# %% ../nbs/01_viz.ipynb 6
def trace(root:Value):# root node of the computation graph
    '''builds a set of all nodes and edges in a graph'''
    nodes, edges = set(), set()
    def build(v):
        if v not in nodes:
            nodes.add(v)
            for child in v._prev:
                edges.add((child, v))
                build(child)
    build(root)
    return nodes, edges

# %% ../nbs/01_viz.ipynb 7
def draw_dot(root:Value,# root node of the computation graph 
             format='svg',# png | svg | ... 
             rankdir='LR'):# TB (top to bottom graph) | LR (left to right)
    """
    visualize the graph using dot
    """
    assert rankdir in ['LR', 'TB']
    nodes, edges = trace(root)
    dot = Digraph(format=format, graph_attr={'rankdir': rankdir}) #, node_attr={'rankdir': 'TB'})
    
    for n in nodes:
        # for any value in the graph, create a rectangular (`record`) node for it         
        dot.node(name=str(id(n)), label = f'{n.label} | data {n.data:.4f} | grad {n.grad:.4f}', shape='record')
        if n._op:
            # if this value is the result of some operation create an op node for it
            dot.node(name=str(id(n)) + n._op, label=n._op)
            # and connect this node to it
            dot.edge(str(id(n)) + n._op, str(id(n)))
    
    for n1, n2 in edges:
        # connect n1 to the op node of n2
        dot.edge(str(id(n1)), str(id(n2)) + n2._op)
    
    return dot
