# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_viz.ipynb.

# %% auto 0
__all__ = ['trace', 'draw_dot']

# %% ../nbs/01_viz.ipynb 2
from .engine import *
from graphviz import Digraph

# %% ../nbs/01_viz.ipynb 4
def trace(root):
    nodes, edges = set(), set()
    def build(v):
        if v not in nodes:
            nodes.add(v)
            for child in v._prev:
                edges.add((child, v))
                build(child)
    build(root)
    return nodes, edges

# %% ../nbs/01_viz.ipynb 5
def draw_dot(root, 
             format='svg',# png | svg | ... 
             rankdir='LR'):# TB (top to bottom graph) | LR (left to right)
    """
    visualize the graph using dot
    """
    assert rankdir in ['LR', 'TB']
    nodes, edges = trace(root)
    dot = Digraph(format=format, graph_attr={'rankdir': rankdir}) #, node_attr={'rankdir': 'TB'})
    
    for n in nodes:
        dot.node(name=str(id(n)), label = "{ data %.4f | grad %.4f }" % (n.data, n.grad), shape='record')
        if n._op:
            dot.node(name=str(id(n)) + n._op, label=n._op)
            dot.edge(str(id(n)) + n._op, str(id(n)))
    
    for n1, n2 in edges:
        dot.edge(str(id(n1)), str(id(n2)) + n2._op)
    
    return dot
